name: Go deploy
on:
  push:
    #tags:
      #- "v*.*.*"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Test
      run: go test -v ./...
  deploy:
    runs-on: ubuntu-latest
    # needsで直列実行指定。ここではtestジョブの後に実行
    needs: test
    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v2
      # イメージビルドにBuildkitを有効か
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # イメージのビルドとpush
      - name: Build and push Docker image
        run: |
          TAG=$(echo $GITHUB_REF | grep -o "[0-9][\.].*")
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/greeting:$TAG
          docker login --usename ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD}}
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
